name: Thermen Tracker

on:
  schedule:
    - cron: '0 7 * * *'
    - cron: '0 12 * * *'
    - cron: '0 17 * * *'

  workflow_dispatch:

jobs:
  track:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test
        run: echo "GitHub Actions funktioniert"
